### ISSUE TITLE
Soundcloud and livestreaming don't work

### ISSUE THREAD

**Issue by kuekerino** [DomT4/homebrew-chromium#5]
I downloaded this version of chromium following the instructions found here:

https://apple.stackexchange.com/questions/78805/chromium-builds-for-mac-os-x/215426#215426

Trying to play something on soundcloud or watching a live stream on youtube does not work.

On soundcloud it keeps cycling through the tracks without playing anything and on youtube the screen stays black. Normal videos on youtube work though. 

I updated my brew before running the commands

**Comment by DomT4** [comment]
Chromium, unlike Chrome, isn't shipped with support for various codecs, I believe for licensing reasons. This includes things like MP3, H.264 & AAC. I presume Soundcloud is using MP3 & YouTube livestreaming uses MP4/AAC, which would explain the failures there.

You can see the difference in `ffmpeg` flags they pass [here](https://www.chromium.org/audio-video) depending on the browser's branding, with Chromium shipping only the default set of codecs. You can also see a lot of the differences by running the [HTML5 Test](https://html5test.com/) website.

It's possible if you built Chromium from source you'd be able to flip flags around to get that support, but doing so would make Chromium non-free. For better or worse I'm afraid I have no plans to add a from-source Chromium formula for this tap because building Chromium from source is _incredibly painful_ and would be a complete nightmare to build locally every ~10 days 😢.

This isn't something I have the power to fix, at least as far as I'm aware, I'm afraid. Sorry I can't be more helpful on this.
