### ISSUE TITLE
Google API keys missing?

### ISSUE THREAD

**Issue by ryanpcmcquen** [DomT4/homebrew-chromium#6]
I get this everytime I launch Chromium. It's probably the reason I cannot log in to Chromium ...

Is there a way to fix this?
![screen shot 2017-10-17 at 3 41 23 pm](https://user-images.githubusercontent.com/772937/31693107-b325e562-b351-11e7-838e-9fd873321eb8.png)

**Comment by DomT4** [comment]
> I get this everytime I launch Chromium.

This is expected, FWIW. It's not specific to this tap or the version of Chromium we're using.

> Is there a way to fix this?

Not from the GUI. If you install the formula `--with-exec-script` you can do something like:
```
GOOGLE_API_KEY="no" GOOGLE_DEFAULT_CLIENT_ID="no" GOOGLE_DEFAULT_CLIENT_SECRET="no" chromium
```
from the terminal to suppress the message. Of course, even without the exec script you can do the same thing with a shell alias or such.

If you want the functionality that needs the API keys you can obtain them as detailed [here](https://www.chromium.org/developers/how-tos/api-keys) and then use those same variables but with legitimate rather than bogus input.

**Comment by ryanpcmcquen** [comment]
Thank you @DomT4!
